#!/usr/bin/env ruby
# frozen_string_literal: true

files = []
Dir.foreach('.') do |item|
  next if item.match?(/^\..*/)

  files << item
end

files = files.sort
file_lengths = []
files.each do |file|
  file_lengths << file.length
end

number_of_columns = 3
n = number_of_columns - 1
indexes = []
1.upto(n) { |x| indexes << x }

quotient, remainder = files.length.divmod(number_of_columns)
files_transposed =
  if remainder != 0
    (number_of_columns - remainder).times do
      files << nil
    end
    files.each_slice(quotient + 1).to_a.transpose
  else
    files.each_slice(quotient).to_a.transpose
  end

files_transposed.each do |column|
  column_array = [column[0].to_s.ljust(file_lengths.max)]
  indexes.each do |i|
    column_array << column[i].to_s.ljust(file_lengths.max)
  end
  puts column_array.join(' ' * 4)
end
